const arrSuperheroes = [{
    name: "Бэтмен",
    universe: "DC Comics",
    alterEgo: "Брюс Уэйн",
    occupation: "борец с преступностью, филантроп, миллиардер",
    friends: "Робин, Бэтгерл",
    superpowers: "интеллект, обширные познания, знания боевых искусств, ловкость",
    picture: "assets/batman.jpg",
    }, {name: "Супермен",
    universe: "DC Comics",  
    alterEgo: "Кларк Кент",
    occupation: "борец за справедливость",
    friends: "собака Крипто",
    superpowers: "непробиваемость, суперсила, полет, самоисцеление, суперзрение и суперслух, классный костюм",
    picture: "assets/superman.jpg",
    }, {name: "Железный человек",
    universe: "Marvel Comics",
    alterEgo: "Тони Старк",
    occupation: "гений, миллиардер, плейбой, филантроп",
    friends: "Мстители",
    superpowers: "высокий уровень интеллекта, широкие познания науки и техники, связь со всемирной паутиной, бронекостюмы",
    picture: "assets/ironman.jpg",
    }, {name: "Человек-паук",
    universe: "Marvel Comics",
    alterEgo: "Питер Паркер",
    occupation: "борец за справедливость, студент, фотограф",
    friends: "Мстители, Фантастическая четверка, Люди Икс",
    superpowers: "сверхчеловеческие рефлексы, «паучье чутье», способность прилепляться к твердым поверхностям, производство паутины",
    picture: "assets/spiderman.jpg",
    }, {name: "Тор",
    universe: "Marvel Comics",
    alterEgo: "Тор Одинсон",
    occupation: "борец за справедливость, скандинавский бог",
    friends: "Мстители",
    superpowers: "все, что может бог, плюс молот Мьелнир",
    picture: "assets/thor.jpg",
    }]